# fly.toml app configuration file generated for fullstackpokedex on 2023-09-23T15:13:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackpokedex"
primary_region = "arn"

[build]

[deploy]
  release_command = "npm run build"
  strategy = "immediate"

[processes]
  app = "node app.js"

[[services]]
  protocol = ""
  internal_port = 3000
  processes = ["app"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
