# fly.toml app configuration file generated for fullstackpokedex on 2023-09-22T14:38:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackpokedex"
primary_region = "arn"

[build]

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"
