# fly.toml app configuration file generated for fullstackpokedex on 2023-09-22T14:38:50+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstackpokedex"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    [NODE_VERSION] = "16.20.2"

[[services]]
  [http_checks] = []
  internal_port = 8080
  processes = ["app"]
