name:  Health check

on: 
  push:
    branches: [master]
  # schedule:
  #  - cron: '30 5 * * 1,3'

jobs: 
  steps:
    name: URL Health Check      
    uses: Jtalk/url-health-check-action@v3.2
    with:
      url: https://fullstackpokedex.fly.dev
